#!/bin/sh
/usr/local/bin/jekyll build --source blog/ --dest /var/www/stb-blog/ 
/usr/local/bin/jekyll build --source models/ --dest /var/www/models/
# /usr/local/bin/jekyll build --source vwsite/ --dest /var/www/vwsite/

